version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  springboot-app:
    image: beyza201511/devops-project:latest
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://admin:test@cluster0.bz4besm.mongodb.net/AmazeStay?retryWrites=true&w=majority
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local
